#!/bin/bash

# current dir
currentDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# library dir
libraryDir="$currentDir/src/lib"
export PYTHONPATH="$libraryDir:$PYTHONPATH"

# running all tests
coverage run --include "src/lib/chilopoda/*" -m unittest discover -p "*Test.py" -v
coverage report -m
coverage html
