#!/bin/bash

# current dir
currentDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# library dir
libraryDir="$currentDir/src/lib"

case "$(uname -s)" in
  CYGWIN*|MINGW**)
    export PYTHONPATH="$(CYGPATH -w $libraryDir);$PYTHONPATH"
    ;;
  *)
    export PYTHONPATH="$libraryDir:$PYTHONPATH"
    ;;
esac

# figuring out which python is going to be used for the
# execution
if [[ -z "$KOMBI_PYTHON_EXECUTABLE" ]]; then
  export KOMBI_PYTHON_EXECUTABLE="python"
fi

# running all tests
$KOMBI_PYTHON_EXECUTABLE -m unittest discover -v
